In [5]:
import pandas as pd

df = pd.read_excel("gv_m_pop-.xlsx")

In [8]:
df

,시군구코드,시군구명,"WGS84좌표, X좌표값","WGS84좌표, Y좌표값",조사일시,월요일,화요일,수요일,목요일,금요일,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,41220,평택시,126.969610,37.045124,201509,0.025304,0.034683,0.037586,0.032253,0.030677,...,0.012213,0.012294,0.012052,0.015647,0.010049,0.009714,0.009466,0.006447,0.004421,0.003290
1,11350,노원구,127.060340,37.639175,201509,97.232959,130.566245,139.167120,111.941891,113.090415,...,47.846447,51.892382,56.121037,59.201168,56.982429,50.508933,44.139848,40.146118,30.527234,18.728765
2,11560,영등포구,126.939010,37.520008,201509,2032.897143,2753.325714,2996.748571,2424.857143,2432.120000,...,1120.588571,1139.331429,1107.937143,1103.251429,1127.851429,848.817143,649.674286,572.594286,446.314286,291.451429
3,41150,의정부시,127.040050,37.737648,201509,0.027465,0.027465,0.000000,0.000000,0.027465,...,0.000000,0.027465,0.027465,0.000000,0.000000,0.000000,0.000000,0.000000,0.027465,0.000000
4,11140,중구,126.974600,37.561170,201509,514.638239,727.688560,867.926942,722.087642,717.563823,...,372.676498,343.594806,344.456485,332.177549,264.751107,129.467385,55.147505,33.605511,20.680314,11.848097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11640,11305,강북구,127.014595,37.640910,201509,143.163110,180.199787,194.448040,153.701109,163.536575,...,75.917503,74.051399,80.659602,81.823173,81.889036,72.382882,62.679141,53.436438,40.307847,24.434986
11641,11560,영등포구,126.903915,37.516960,201509,83.591698,96.509444,120.103014,84.445764,115.832685,...,38.539723,49.002030,51.457469,71.421259,72.168567,104.623070,73.983457,54.019667,52.204777,12.490713
11642,11140,중구,126.974945,37.558850,201509,4692.153086,6520.461977,7597.232670,6132.911339,6029.047768,...,2874.695614,2952.825822,2856.093183,2805.556580,2933.913351,1901.478451,1157.381226,899.427521,678.988718,492.344331
11643,11500,강서구,126.806984,37.563343,201509,116.581136,148.991321,156.587094,126.693300,133.788125,...,61.721481,63.678674,65.705766,70.796798,76.144129,64.668920,53.426710,46.145486,40.169057,23.544566
11644,11740,강동구,127.167076,37.552060,201509,276.674432,342.283052,367.574257,291.001747,303.931276,...,140.084450,138.861386,150.131043,146.811299,148.689575,130.736750,115.928946,101.820035,78.974956,54.775772

In [9]:
df.columns

Index(['시군구코드', '시군구명', 'WGS84좌표, X좌표값', 'WGS84좌표, Y좌표값', '조사일시', '월요일', '화요일',
       '수요일', '목요일', '금요일', '토요일', '일요일', '1~14세', '15~19세', '20~24세',
       '25~29세', '30~34세', '35~39세', '40~44세', '45~49세', '50~54세', '55~59세',
       '60세이상', '1~14세.1', '15~19세.1', '20~24세.1', '25~29세.1', '30~34세.1',
       '35~39세.1', '40~44세.1', '45~49세.1', '50~54세.1', '55~59세.1', '60세이상.1',
       '0시', '1시', '2시', '3시', '4시', '5시', '6시', '7시', '8시', '9시', '10시',
       '11시', '12시', '13시', '14시', '15시', '16시', '17시', '18시', '19시', '20시',
       '21시', '22시', '23시'],
      dtype='object')

In [7]:
df["시군구명"].unique()

array(['평택시', '노원구', '영등포구', '의정부시', '중구', '서초구', '시흥시', '수원시 권선구',
       '성남시 수정구', '도봉구', '화성시', '수원시 영통구', '동작구', '양천구', '강서구', '포천시',
       '동대문구', '송파구', '강남구', '구로구', '용인시기흥구', '성동구', '부천시원미구', '남양주시',
       '양주시', '서구', '의왕시', '계양구', '성남시 중원구', '동구', '광명시', '연수구', '금천구',
       '수원시 장안구', '양평군', '안양시동안구', '수원시 팔달구', '안양시만안구', '광진구', '은평구',
       '관악구', '용인시처인구', '종로구', '마포구', '이천시', '부천시오정구', '중랑구', '부평구',
       '용산구', '남구', '고양시일산동구', '서대문구', '용인시수지구', '오산시', '성북구', '남동구',
       '옹진군', '하남시', '강동구', '성남시 분당구', '고양시덕양구', '가평군', '구리시', '부천시소사구',
       '안산시상록구', '안성시', '강화군', '고양시일산서구', '군포시', '파주시', '안산시단원구', '광주시',
       '과천시', '강북구', '여주시', '연천군', '김포시', '동두천시'], dtype=object)

In [10]:
df.sort_values(by="19시")

,시군구코드,시군구명,"WGS84좌표, X좌표값","WGS84좌표, Y좌표값",조사일시,월요일,화요일,수요일,목요일,금요일,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
1591,11680,강남구,127.058180,37.507812,201509,0.00000,0.000000,0.000000,0.192074,0.000000,...,0.000000,0.00000,0.00000,0.00000,0.192074,0.00000,0.00000,0.00000,0.000000,0.000000
6731,11170,용산구,126.971504,37.542290,201509,0.00000,0.000000,0.137713,0.137713,0.000000,...,0.137713,0.00000,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000
1782,41131,성남시 수정구,127.129720,37.435290,201509,0.00000,0.155994,0.311989,0.000000,0.000000,...,0.155994,0.00000,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000
4334,11680,강남구,127.057550,37.510597,201509,0.00000,0.000000,0.000000,0.000000,0.043796,...,0.000000,0.00000,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000
401,11680,강남구,127.036804,37.509950,201509,0.00000,0.155180,0.077590,0.077590,0.000000,...,0.000000,0.00000,0.00000,0.00000,0.077590,0.00000,0.00000,0.00000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4644,41135,성남시 분당구,127.125930,37.386425,201509,31484.00000,41490.000000,45449.000000,36964.000000,36773.000000,...,16051.000000,16506.00000,17415.00000,17709.00000,16138.000000,13659.00000,10959.00000,9153.00000,7399.000000,5251.000000
7421,41131,성남시 수정구,127.129000,37.435535,201509,28292.00000,36726.000000,38018.000000,32091.000000,33931.000000,...,13796.000000,14228.00000,15409.00000,17553.00000,18174.000000,14273.00000,11413.00000,10019.00000,7763.000000,5102.000000
6303,28200,남동구,126.738304,37.400635,201509,28421.25229,35439.324520,36473.468350,29207.269580,31058.588150,...,15079.352280,15793.70746,16406.65932,17061.24886,16885.634180,14588.19769,12264.70225,10651.87974,7738.092399,5271.839223
9461,41195,부천시원미구,126.752270,37.504160,201509,31598.00000,40837.000000,43270.000000,33884.000000,37016.000000,...,18612.000000,19319.00000,19794.00000,20662.00000,20444.000000,17198.00000,14049.00000,11702.00000,8195.000000,4801.000000
591,41450,하남시,127.203210,37.540554,201509,39404.18182,50701.090910,52997.454550,43604.727270,45652.909090,...,20210.181820,20580.00000,21559.63636,22314.00000,23079.272730,19463.45455,15529.63636,13414.36364,9573.818182,6253.636364