In [56]:
import random
import pandas as pd

service_tasks = [
    ["토너교체", "무상", 0, 0],
    ["청소", "무상", 0, 0],
    ["주유", "무상", 0, 0],
    ["드럼교체", "무상", 0, 0],
    ["드럼교체(고객과실)", "유상", 500000, 550000],
    ["용지걸림 수리", "무상", 0, 0],
    ["용지걸림 수리(고객과실)", "유상", 35000, 50000],
    ["급지트레이 교체", "무상", 0, 0],
    ["급지트레이 교체(고객과실)", "유상", 40000, 50000],
    ["스캐너 교체", "무상", 0, 0],
    ["스캐너 교체(고객과실)", "유상", 350000, 450000],
    ["메인보드 교체", "무상", 0, 0],
    ["메인보드 교체(고객과실)", "유상", 250000, 350000],
    ["온도센서 교체", "무상", 0, 0],
    ["온도센서 교체(고객과실)", "유상", 30000, 50000],
    ["기타센서 교체", "무상", 0, 0],
    ["기타센서 교체(고객과실)", "유상", 20000, 80000],
    ["커버파손 교체(고객과실)", "유상", 30000, 80000],
    ["바퀴 교체", "무상", 0, 0]
]

date_list = ["04", "05", "06", "07", "08", "11", "12", "13", "14", "15", "18", "19", "20", "21", "22", "25", "26", "27", "28", "29"]
service_result = []

for i in range(8):
    for t in range(random.randrange(40, 60)):
        rand_no = random.randrange(0, len(service_tasks))
        if service_tasks[rand_no][1] == "유상":
            price = random.randrange(service_tasks[rand_no][2], service_tasks[rand_no][3], 1000)
        else:
            price = service_tasks[rand_no][2]
        vat = int(price/10)
        total_price = int(price + vat)
        this_service_result = {
            "기사" : "기사{}".format(i+1),
            "서비스일자" : "2021-10-{}".format(date_list[random.randrange(len(date_list))]),
            "서비스명" : service_tasks[rand_no][0],
            "유상/무상" : service_tasks[rand_no][1],
            "비용(공급단가)" : price,
            "비용(부가세)" : vat,
            "비용(총비용)" : total_price
        }
        service_result.append(this_service_result)
df = pd.DataFrame(service_result)
df.to_excel("서비스 이력 샘플.xlsx", index=False)
print("유상 건수 : {}".format(len(df[df["유상/무상"].isin(["유상"])])))
print("무상 건수 : {}".format(len(df[df["유상/무상"].isin(["무상"])])))
df

유상 건수 : 187
무상 건수 : 239

      기사       서비스일자           서비스명 유상/무상  비용(공급단가)  비용(부가세)  비용(총비용)
0    기사1  2021-10-28        용지걸림 수리    무상         0        0        0
1    기사1  2021-10-11  온도센서 교체(고객과실)    유상     49000     4900    53900
2    기사1  2021-10-15         스캐너 교체    무상         0        0        0
3    기사1  2021-10-04         스캐너 교체    무상         0        0        0
4    기사1  2021-10-04           드럼교체    무상         0        0        0
..   ...         ...            ...   ...       ...      ...      ...
421  기사8  2021-10-12  용지걸림 수리(고객과실)    유상     39000     3900    42900
422  기사8  2021-10-20       급지트레이 교체    무상         0        0        0
423  기사8  2021-10-27        기타센서 교체    무상         0        0        0
424  기사8  2021-10-20         스캐너 교체    무상         0        0        0
425  기사8  2021-10-12       급지트레이 교체    무상         0        0        0

[426 rows x 7 columns]